// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHx52rYJNHDVpa-XgfI-xwE4pCy7rYubQ',
    appId: '1:82166629686:web:f00bd8d35e83186189df97',
    messagingSenderId: '82166629686',
    projectId: 'app-11cda',
    authDomain: 'app-11cda.firebaseapp.com',
    storageBucket: 'app-11cda.appspot.com',
    measurementId: 'G-5S700C97WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGh3rZ6WJWO7ZQ6LYwoTZjO4t-agczSa0',
    appId: '1:82166629686:android:337850c9526cbfe089df97',
    messagingSenderId: '82166629686',
    projectId: 'app-11cda',
    storageBucket: 'app-11cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6jbOrn2Z1udRKZRHeqOic6vUJlYsHp4',
    appId: '1:82166629686:ios:4fb9f98128b35c0389df97',
    messagingSenderId: '82166629686',
    projectId: 'app-11cda',
    storageBucket: 'app-11cda.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6jbOrn2Z1udRKZRHeqOic6vUJlYsHp4',
    appId: '1:82166629686:ios:4fb9f98128b35c0389df97',
    messagingSenderId: '82166629686',
    projectId: 'app-11cda',
    storageBucket: 'app-11cda.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHx52rYJNHDVpa-XgfI-xwE4pCy7rYubQ',
    appId: '1:82166629686:web:6d8ba019be6a80d289df97',
    messagingSenderId: '82166629686',
    projectId: 'app-11cda',
    authDomain: 'app-11cda.firebaseapp.com',
    storageBucket: 'app-11cda.appspot.com',
    measurementId: 'G-YGY0FE15D8',
  );
}
